# Generated by Django 5.1.4 on 2025-01-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_president',
            field=models.BooleanField(default=False),
        ),
    ]
