# Generated by Django 5.1.4 on 2025-01-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sibya', '0002_user_is_president'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user',
            new_name='author',
        ),
    ]
