# Generated by Django 5.1.4 on 2025-01-04 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibya', '0003_rename_user_notice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
