# Generated by Django 5.1.4 on 2025-01-09 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibya', '0006_historicalnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='participants',
        ),
        migrations.AddField(
            model_name='notice',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
