# Generated by Django 5.1.4 on 2025-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibya', '0011_historicalorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotice',
            name='type',
            field=models.CharField(choices=[('Recruitment', 'Recruitment'), ('Event', 'Event')], max_length=45),
        ),
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('Recruitment', 'Recruitment'), ('Event', 'Event')], max_length=45),
        ),
    ]
